services:
  mc-daemon:
    build: .
    container_name: mcdaemon
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "25565:25565"
    environment:
      - MC_CONFIG=prod.toml
    volumes:
      - ./runtime/server:/app/server
      - ./runtime/backups:/app/backups
      - ./configs/prod.toml:/app/prod.toml
    deploy:
      resources:
        limits:
          memory: 6G
