[package]
name = "mc_daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# IMPORTANTE: Así vinculamos tu librería local
mc_process = { path = "../mc_process" }
mc_config = { path = "../mc_config" }
